### ISSUE TITLE
data_utils.py failed with error

### ISSUE THREAD

**Issue by VVCepheiA** [DevinZ1993/Chinese-Poetry-Generator#1]
Hi, I was trying out the code after reading the paper. It seems like some of the data processing step failed. After running data_utils, there was only one output (sxhy_dict.txt) in the data folder, and gave the following error:

```
(tensorflow2) Vera-MacBook-Pro:Chinese-Poetry-Generation Vera$ python data_utils.py

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/rj/yxfk4xl915l_0drx9d_stdgh0000gn/T/jieba.cache
Loading model cost 1.845 seconds.
Prefix dict has been built succesfully.
Generating the vocabulary ...
Parsing raw/qts_tab.txt ...
Traceback (most recent call last):
  File "data_utils.py", line 127, in <module>
    train_data = get_train_data()
  File "data_utils.py", line 72, in get_train_data
    _gen_train_data()
  File "data_utils.py", line 34, in _gen_train_data
    poems = get_pop_quatrains()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/cnt_words.py", line 40, in get_pop_quatrains
    cnts = get_word_cnts()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/cnt_words.py", line 27, in get_word_cnts
    _gen_word_cnts()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/cnt_words.py", line 14, in _gen_word_cnts
    quatrains = get_quatrains()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/quatrains.py", line 21, in get_quatrains
    _, ch2int = get_vocab()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/vocab.py", line 31, in get_vocab
    _gen_vocab()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/vocab.py", line 15, in _gen_vocab
    corpus = get_all_corpus()
  File "/Users/Vera/Documents/projects/ura/Chinese-Poetry-Generation/corpus.py", line 63, in get_all_corpus
    corpus.extend(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

Below is the lists of packages installed:
```
# packages in environment at /anaconda/envs/tensorflow2:
#
boto                      2.46.1                    <pip>
bz2file                   0.98                      <pip>
funcsigs                  1.0.2                     <pip>
gensim                    2.1.0                     <pip>
jieba                     0.38                      <pip>
mock                      2.0.0                     <pip>
numpy                     1.12.1                    <pip>
openssl                   1.0.2k                        2  
pbr                       3.0.1                     <pip>
pip                       9.0.1                    py27_1  
pip                       9.0.1                     <pip>
protobuf                  3.3.0                     <pip>
python                    2.7.13                        0  
readline                  6.2                           2  
requests                  2.14.2                    <pip>
scipy                     0.19.0                    <pip>
setuptools                27.2.0                   py27_0  
six                       1.10.0                    <pip>
smart-open                1.5.3                     <pip>
sqlite                    3.13.0                        0  
tensorflow                1.1.0                     <pip>
tk                        8.5.18                        0  
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3
```

Any suggestion?

**Comment by DevinZ1993** [comment]
Could you surround line 61 of corpus.py with a "try...except" statement and run it again? I mean simply to catch an  from there and print it out so that we can further pinpoint the problem. I guess there must be something wrong with _parse_corpus() ...

**Comment by VVCepheiA** [comment]
So it seems like the problem is the `unichr` function in rhyme.py is not supported by narrow build of Python. It can be resolved by rebuilding wide Python yourself (painful, **DON'T**) or simply adding `import struct`, and use the following function instead:
```
def unichar(i):
    try:
        return unichr(i)
    except ValueError:
        return struct.pack('i', i).decode('utf-32')
```
